ApplicationDev/Models/Category.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ApplicationDev.Models
{
    public class Category
    {
		public int ID { get; set; }

		[Required]
		[StringLength(255)]
		public string Name { get; set; }

		[Required]
		[StringLength(255)]
		public string Description { get; set; }
	}
}

ApplicationDev/Controllers/CategoryController.cs
using ApplicationDev.Models;
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace AsmAppDev2.Controllers
{
	public class CategoriesController : Controller
	{
		private ApplicationDbContext _context;

		public CategoriesController()
		{
			_context = new ApplicationDbContext();
		}
		// GET: Categories
		[HttpGet]
		
		public ActionResult Index(string searchString)
		{
			var category = _context.Category.ToList();

			if (!String.IsNullOrEmpty(searchString))
			{
				category = category.FindAll(s => s.Name.Contains(searchString));
			}

			return View(category);
		}

		////GET: View Categories Details
		//public ActionResult Details(int? id)
		//{
		//	if (id == null)
		//	{
		//		return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
		//	}
		//	Category category = _context.Categories.Find(id);
		//	if (category == null)
		//	{
		//		return HttpNotFound();
		//	}
		//	return View(category);
		//}

		//GET: Create 
		[HttpGet]
	
		public ActionResult Create()
		{
			return View();
		}

		[HttpPost]

		public ActionResult Create(Category category)
		{
			if (!ModelState.IsValid)
			{
				return RedirectToAction("Create");
			}
			var check = _context.Category.Any(
				c => c.Name.Contains(category.Name));
			if (check)
			{
				ModelState.AddModelError("", "Category Already Exists.");
				return View("Create");
			}
			_context.Category.Add(category);
			_context.SaveChanges();
			return RedirectToAction("Index");
		}

		//GET: Edit
		[HttpGet]

		public ActionResult Edit(int? id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			Category category = _context.Category.Find(id);
			if (category == null)
			{
				return HttpNotFound();
			}
			return View();
		}

		[HttpPost]
		public ActionResult Edit(Category category)
		{

			if (ModelState.IsValid)
			{
				_context.Entry(category).State = EntityState.Modified;
				_context.SaveChanges();
				return RedirectToAction("Index");
			}
			var check = _context.Category.Any(
				c => c.Name.Contains(category.Name));

			if (check)
			{
				ModelState.AddModelError("", "Category Already Exists.");
				return View("Index");
			}
			category.Name = category.Name;
			category.Description = category.Description;
			return View(category);
		}

		//GET: Delete
		[HttpGet]

		public ActionResult Delete(int id)
		{
			var categoryInDb = _context.Category.SingleOrDefault(c => c.ID == id);

			if (categoryInDb == null)
			{
				return HttpNotFound();
			}

			_context.Category.Remove(categoryInDb);
			_context.SaveChanges();
			return RedirectToAction("Index");
		}
	}
}

ApplicationDev/Controllers/TraineeUsersController.cs
using ApplicationDev.Models;
using ApplicationDev.Utils;
using ApplicationDev.ViewModel;
using Microsoft.AspNet.Identity;
using System;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;


namespace ApplicationDev.Controllers
{
	[Authorize(Roles = Role.Manager)]
	public class TraineeUsersController : Controller
	{
		

		private ApplicationDbContext _context;
		public TraineeUsersController()
		{
			_context = new ApplicationDbContext();
		}
		// GET: Trainees
		[HttpGet]
		public ActionResult Index(string searchString)
		{
			var trainee = _context.TraineeUsers.Include(te => te.Trainees);
			if (!String.IsNullOrEmpty(searchString))
			{
				trainee = trainee.Where(s => s.Trainees.UserName.Contains(searchString));
				return View(trainee);
			}

			if (User.IsInRole(Role.Manager))
			{
				var viewTrainee = _context.TraineeUsers.Include(a => a.Trainees).ToList();
				return View(viewTrainee);
			}
		/*	if (User.IsInRole("Trainee"))
			{
				var traineeId = User.Identity.GetUserId();
				var traineeVM = _context.TraineeUsers.Where(te => te.TraineeID == traineeId).ToList();
				return View(traineeVM);
			}*/
			return View("Index");

		}
		// CREATE
		[HttpGet]
		public ActionResult Create()
		{
			//Get Account Trainee
			var userInDb = (from r in _context.Roles where r.Name.Contains("Trainee") select r).FirstOrDefault();
			var users = _context.Users.Where(u => u.Roles.Select(us => us.RoleId).Contains(userInDb.Id)).ToList();
			var traineeUser = _context.TraineeUsers.ToList();
			var viewModel = new TraineeUserViewModel
			{
				Trainees = users,
				TraineeUser = new Trainee()
			};
			return View(viewModel);
		}
		[HttpPost]
		public ActionResult Create(TraineeUserViewModel trainee)
		{
			var traineeinDb = (from te in _context.Roles where te.Name.Contains("Trainee") select te).FirstOrDefault();
			var traineeUser = _context.Users.Where(u => u.Roles.Select(us => us.RoleId).Contains(traineeinDb.Id)).ToList();
			if (ModelState.IsValid)
			{

				var checkTraineeExist = _context.TraineeUsers.Include(t => t.Trainees).Where(t => t.Trainees.Id == trainee.TraineeUser.TraineeID);
				//GET TraineeID 
				if (checkTraineeExist.Count() > 0)  //list ID comparison, if count == 0. jump to else
													// if (checkTraineeExist.Any())
				{
					ModelState.AddModelError("", "Trainee Already Exists.");
				}
				else
				{
					_context.TraineeUsers.Add(trainee.TraineeUser);
					_context.SaveChanges();
					return RedirectToAction("Index");
				}
			}
			TraineeUserViewModel traineeUserView = new TraineeUserViewModel()
			{
				Trainees = traineeUser,
				TraineeUser = trainee.TraineeUser
			};
			return View(traineeUserView);
		}


		[HttpGet]
		public ActionResult Edit(int id)
		{
			var traineeInDb = _context.TraineeUsers.SingleOrDefault(te => te.ID == id);
			if (traineeInDb == null)
			{
				return HttpNotFound();
			}
			return View(traineeInDb);
		}

		[HttpPost]
		public ActionResult Edit(Trainee traineeUser)
		{
			if (!ModelState.IsValid)
			{
				return View();
			}
			var traineeInDb = _context.TraineeUsers.SingleOrDefault(te => te.ID == traineeUser.ID);
			if (traineeInDb == null)
			{
				return HttpNotFound();
			}
			traineeInDb.Email = traineeUser.Email;
			traineeInDb.Full_Name = traineeUser.Full_Name;
			traineeInDb.Age = traineeUser.Age;
			traineeInDb.DateOfBirth = traineeUser.DateOfBirth;
			traineeInDb.Education = traineeUser.Education;
			//traineeInDb.Phone = traineeUser.Phone;
			_context.SaveChanges();
			return RedirectToAction("Index");
		}
		[HttpGet]
		public ActionResult Delete(int id)
		{
			var traineeInDb = _context.TraineeUsers.SingleOrDefault(te => te.ID == id);
			if (traineeInDb == null)
			{
				return HttpNotFound();
			}
			_context.TraineeUsers.Remove(traineeInDb);
			_context.SaveChanges();
			return RedirectToAction("Index");
		}
	}
}

ApplicationDev/Views/Categories/Create.cshtml
@model ApplicationDev.Models.Category
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

<h2>Create</h2>
@Html.AntiForgeryToken()
@Html.ValidationSummary(false, "", new { @class = "text-danger" })
@using (Html.BeginForm())
{

    <div class="form-group">
        @Html.LabelFor(c => c.Name)
        @Html.TextBoxFor(c => c.Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(c => c.Name)
    </div>

    <div class="form-group">
        @Html.LabelFor(c => c.Description)
        @Html.TextBoxFor(c => c.Description, new { @class = "form-control" })
        @Html.ValidationMessageFor(c => c.Description)
    </div>
    <button type="submit" class="btn btn-default">Create</button>
}

@Html.ActionLink("Back to List", "Index")

ApplicationDev/Views/Categories/Edit.cshtml
@model ApplicationDev.Models.Category
@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.HiddenFor(c => c.ID)
    <div class="form-group">
        @Html.LabelFor(c => c.Name)
        @Html.EditorFor(c => c.Name, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(c => c.Name, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(c => c.Description)
        @Html.EditorFor(c => c.Description, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(c => c.Description, "", new { @class = "text-danger" })
    </div>
    <button type="submit" class="btn btn-default">Edit</button>
}

@Html.ActionLink("Back to List", "Index")

ApplicationDev/Views/Categories/Index.cshtml
@model IEnumerable<ApplicationDev.Models.Category>
@{
    ViewBag.Title = "Index";
}

<h2>Category</h2>
@using (Html.BeginForm("Index", "Categories", FormMethod.Get))
{
    <p>
        Find by name: @Html.TextBox("SearchString")
        <input type="submit" value="Search" />
    </p>
}

    @Html.ActionLink("Create New Category", "Create")

    <table class="table">
        <tr>
            <th scope="col">#</th>
            <th>Category</th>
            <th>Description</th>
            <th>Edit</th>
            <th>Delete</th>

        </tr>

        @foreach (var category in Model)
        {
    <tr>
        <td>@category.ID</td>
        <td>@category.Name</td>
        <td>@category.Description</td>


        <td>@Html.ActionLink("Edit", "Edit", new { id = category.ID })</td>
        <td>@Html.ActionLink("Delete", "Delete", new { id = category.ID })</td>

    </tr>
        }
    </table>


@Html.ActionLink("Back to home", "Index", "TraineeUsers")